# Generated by Django 3.2.5 on 2021-07-06 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210705_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary_per_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='total_working_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='salary_per_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='total_working_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='department',
            name='timestemp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 15, 16, 37, 698400)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='timestemp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 15, 16, 37, 698400)),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='timestemp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 15, 16, 37, 698400)),
        ),
    ]
